import {
  Component,
  OnInit
} from '@angular/core'

import { ChemicalGroup } from 'src/app/enumerations/chemical-group.enumeration'

import { Element } from 'src/app/models/element.model'

const ELEMENT_DATA: Element[] = [
  {atomic:1, symbol:'H', name:'Hydrogen', group:ChemicalGroup.NonMetal, mass:1.0079, weight:1, radioactive:false, artificially:false},
  {atomic:2, symbol:'He', name:'Helium', group:ChemicalGroup.NobleGas, mass:4.0026, weight:4, radioactive:false, artificially:false},
  {atomic:3, symbol:'Li', name:'Lithium', group:ChemicalGroup.AlkaliMetal, mass:6.941, weight:7, radioactive:false, artificially:false},
  {atomic:4, symbol:'Be', name:'Beryllium', group:ChemicalGroup.AlkalineEarthMetal, mass:9.012183, weight:9, radioactive:false, artificially:false},
  {atomic:5, symbol:'B', name:'Boron', group:ChemicalGroup.Metalloid, mass:10.811, weight:11, radioactive:false, artificially:false},
  {atomic:6, symbol:'C', name:'Carbon', group:ChemicalGroup.NonMetal, mass:12.0107, weight:12, radioactive:false, artificially:false},
  {atomic:7, symbol:'N', name:'Nitrogen', group:ChemicalGroup.NonMetal, mass:14.0067, weight:14, radioactive:false, artificially:false},
  {atomic:8, symbol:'O', name:'Oxygen', group:ChemicalGroup.NonMetal, mass:15.9994, weight:16, radioactive:false, artificially:false},
  {atomic:9, symbol:'F', name:'Fluorine', group:ChemicalGroup.Halogen, mass:18.99840316, weight:19, radioactive:false, artificially:false},
  {atomic:10, symbol:'Ne', name:'Neon', group:ChemicalGroup.NobleGas, mass:20.1797, weight:20, radioactive:false, artificially:false},
  {atomic:11, symbol:'Na', name:'Sodium', group:ChemicalGroup.AlkaliMetal, mass:22.9897693, weight:23, radioactive:false, artificially:false},
  {atomic:12, symbol:'Mg', name:'Magnesium', group:ChemicalGroup.AlkalineEarthMetal, mass:24.305, weight:24, radioactive:false, artificially:false},
  {atomic:13, symbol:'Al', name:'Aluminum', group:ChemicalGroup.PostTransitionMetal, mass:26.981538, weight:27, radioactive:false, artificially:false},
  {atomic:14, symbol:'Si', name:'Silicon', group:ChemicalGroup.Metalloid, mass:28.0855, weight:28, radioactive:false, artificially:false},
  {atomic:15, symbol:'P', name:'Phosphorus', group:ChemicalGroup.NonMetal, mass:30.973762, weight:31, radioactive:false, artificially:false},
  {atomic:16, symbol:'S', name:'Sulfur', group:ChemicalGroup.NonMetal, mass:32.065, weight:32, radioactive:false, artificially:false},
  {atomic:17, symbol:'Cl', name:'Chlorin', group:ChemicalGroup.Halogen, mass:35.453, weight:35, radioactive:false, artificially:false},
  {atomic:18, symbol:'Ar', name:'Argon', group:ChemicalGroup.NobleGas, mass:39.948, weight:40, radioactive:false, artificially:false},
  {atomic:19, symbol:'K', name:'Potassium', group:ChemicalGroup.AlkaliMetal, mass:39.0983, weight:39, radioactive:false, artificially:false},
  {atomic:20, symbol:'Ca', name:'Calcium', group:ChemicalGroup.AlkalineEarthMetal, mass:40.078, weight:40, radioactive:false, artificially:false},
  {atomic:21, symbol:'Sc', name:'Scandium', group:ChemicalGroup.TransitionMetal, mass:44.95591, weight:45, radioactive:false, artificially:false},
  {atomic:22, symbol:'Ti', name:'Titanium', group:ChemicalGroup.TransitionMetal, mass:47.867, weight:48, radioactive:false, artificially:false},
  {atomic:23, symbol:'V', name:'Vanadium', group:ChemicalGroup.TransitionMetal, mass:50.9415, weight:51, radioactive:false, artificially:false},
  {atomic:24, symbol:'Cr', name:'Chromium', group:ChemicalGroup.TransitionMetal, mass:51.9961, weight:52, radioactive:false, artificially:false},
  {atomic:25, symbol:'Mn', name:'Manganese', group:ChemicalGroup.TransitionMetal, mass:54.93804, weight:55, radioactive:false, artificially:false},
  {atomic:26, symbol:'Fe', name:'Iron', group:ChemicalGroup.TransitionMetal, mass:55.845, weight:56, radioactive:false, artificially:false},
  {atomic:27, symbol:'Co', name:'Cobalt', group:ChemicalGroup.TransitionMetal, mass:58.93319, weight:59, radioactive:false, artificially:false},
  {atomic:28, symbol:'Ni', name:'Nickel', group:ChemicalGroup.TransitionMetal, mass:58.6934, weight:59, radioactive:false, artificially:false},
  {atomic:29, symbol:'Cu', name:'Copper', group:ChemicalGroup.TransitionMetal, mass:63.546, weight:64, radioactive:false, artificially:false},
  {atomic:30, symbol:'Zn', name:'Zinc', group:ChemicalGroup.TransitionMetal, mass:65.39, weight:65, radioactive:false, artificially:false},
  {atomic:31, symbol:'Ga', name:'Gallium', group:ChemicalGroup.PostTransitionMetal, mass:69.723, weight:70, radioactive:false, artificially:false},
  {atomic:32, symbol:'Ge', name:'Germanium', group:ChemicalGroup.Metalloid, mass:72.64, weight:73, radioactive:false, artificially:false},
  {atomic:33, symbol:'As', name:'Arsenic', group:ChemicalGroup.Metalloid, mass:74.92159, weight:75, radioactive:false, artificially:false},
  {atomic:34, symbol:'Se', name:'Selenium', group:ChemicalGroup.NonMetal, mass:78.96, weight:79, radioactive:false, artificially:false},
  {atomic:35, symbol:'Br', name:'Bromine', group:ChemicalGroup.Halogen, mass:79.904, weight:80, radioactive:false, artificially:false},
  {atomic:36, symbol:'Kr', name:'Krypton', group:ChemicalGroup.NobleGas, mass:83.8, weight:84, radioactive:false, artificially:false},
  {atomic:37, symbol:'Rb', name:'Rubidium', group:ChemicalGroup.AlkaliMetal, mass:85.4678, weight:85, radioactive:false, artificially:false},
  {atomic:38, symbol:'Sr', name:'Strontium', group:ChemicalGroup.AlkalineEarthMetal, mass:87.62, weight:88, radioactive:false, artificially:false},
  {atomic:39, symbol:'Y', name:'Yttrium', group:ChemicalGroup.TransitionMetal, mass:88.90584, weight:89, radioactive:false, artificially:false},
  {atomic:40, symbol:'Zr', name:'Zirconium', group:ChemicalGroup.TransitionMetal, mass:91.224, weight:91, radioactive:false, artificially:false},
  {atomic:41, symbol:'Nb', name:'Niobium', group:ChemicalGroup.TransitionMetal, mass:92.90637, weight:93, radioactive:false, artificially:false},
  {atomic:42, symbol:'Mo', name:'Molybdenum', group:ChemicalGroup.TransitionMetal, mass:95.94, weight:96, radioactive:false, artificially:false},
  {atomic:43, symbol:'Tc', name:'Technetium', group:ChemicalGroup.TransitionMetal, mass:96.90636, weight:98, radioactive:true, artificially:false},
  {atomic:44, symbol:'Ru', name:'Ruthenium', group:ChemicalGroup.TransitionMetal, mass:101.07, weight:101, radioactive:false, artificially:false},
  {atomic:45, symbol:'Rh', name:'Rhodium', group:ChemicalGroup.TransitionMetal, mass:102.9055, weight:103, radioactive:false, artificially:false},
  {atomic:46, symbol:'Pd', name:'Palladium', group:ChemicalGroup.TransitionMetal, mass:106.42, weight:106, radioactive:false, artificially:false},
  {atomic:47, symbol:'Ag', name:'Silver', group:ChemicalGroup.TransitionMetal, mass:107.8682, weight:108, radioactive:false, artificially:false},
  {atomic:48, symbol:'Cd', name:'Cadmium', group:ChemicalGroup.TransitionMetal, mass:112.411, weight:112, radioactive:false, artificially:false},
  {atomic:49, symbol:'In', name:'Indium', group:ChemicalGroup.PostTransitionMetal, mass:114.818, weight:115, radioactive:false, artificially:false},
  {atomic:50, symbol:'Sn', name:'Tin', group:ChemicalGroup.PostTransitionMetal, mass:118.71, weight:119, radioactive:false, artificially:false},
  {atomic:51, symbol:'Sb', name:'Antimony', group:ChemicalGroup.Metalloid, mass:121.76, weight:122, radioactive:false, artificially:false},
  {atomic:52, symbol:'Te', name:'Tellurium', group:ChemicalGroup.Metalloid, mass:127.6, weight:128, radioactive:false, artificially:false},
  {atomic:53, symbol:'I', name:'Iodine', group:ChemicalGroup.Halogen, mass:126.9045, weight:127, radioactive:false, artificially:false},
  {atomic:54, symbol:'Xe', name:'Xenon', group:ChemicalGroup.NobleGas, mass:131.293, weight:131, radioactive:false, artificially:false},
  {atomic:55, symbol:'Cs', name:'Cesium', group:ChemicalGroup.AlkaliMetal, mass:132.905452, weight:133, radioactive:false, artificially:false},
  {atomic:56, symbol:'Ba', name:'Barium', group:ChemicalGroup.AlkalineEarthMetal, mass:137.327, weight:137, radioactive:false, artificially:false},
  {atomic:57, symbol:'La', name:'Lanthanum', group:ChemicalGroup.Lanthanide, mass:138.9055, weight:139, radioactive:false, artificially:false},
  {atomic:58, symbol:'Ce', name:'Cerium', group:ChemicalGroup.Lanthanide, mass:140.116, weight:140, radioactive:false, artificially:false},
  {atomic:59, symbol:'Pr', name:'Praseodymium', group:ChemicalGroup.Lanthanide, mass:140.90766, weight:141, radioactive:false, artificially:false},
  {atomic:60, symbol:'Nd', name:'Neodymium', group:ChemicalGroup.Lanthanide, mass:144.24, weight:144, radioactive:false, artificially:false},
  {atomic:61, symbol:'Pm', name:'Promethium', group:ChemicalGroup.Lanthanide, mass:144.91276, weight:145, radioactive:true, artificially:false},
  {atomic:62, symbol:'Sm', name:'Samarium', group:ChemicalGroup.Lanthanide, mass:150.36, weight:150, radioactive:false, artificially:false},
  {atomic:63, symbol:'Eu', name:'Europium', group:ChemicalGroup.Lanthanide, mass:151.964, weight:152, radioactive:false, artificially:false},
  {atomic:64, symbol:'Gd', name:'Gadolinium', group:ChemicalGroup.Lanthanide, mass:157.25, weight:157, radioactive:false, artificially:false},
  {atomic:65, symbol:'Tb', name:'Terbium', group:ChemicalGroup.Lanthanide, mass:158.92535, weight:159, radioactive:false, artificially:false},
  {atomic:66, symbol:'Dy', name:'Dysprosium', group:ChemicalGroup.Lanthanide, mass:162.5, weight:163, radioactive:false, artificially:false},
  {atomic:67, symbol:'Ho', name:'Holmium', group:ChemicalGroup.Lanthanide, mass:164.93033, weight:165, radioactive:false, artificially:false},
  {atomic:68, symbol:'Er', name:'Erbium', group:ChemicalGroup.Lanthanide, mass:167.259, weight:167, radioactive:false, artificially:false},
  {atomic:69, symbol:'Tm', name:'Thulium', group:ChemicalGroup.Lanthanide, mass:168.93422, weight:169, radioactive:false, artificially:false},
  {atomic:70, symbol:'Yb', name:'Ytterbium', group:ChemicalGroup.Lanthanide, mass:173.05, weight:173, radioactive:false, artificially:false},
  {atomic:71, symbol:'Lu', name:'Lutetium', group:ChemicalGroup.Lanthanide, mass:174.9668, weight:175, radioactive:false, artificially:false},
  {atomic:72, symbol:'Hf', name:'Hafnium', group:ChemicalGroup.TransitionMetal, mass:178.49, weight:178, radioactive:false, artificially:false},
  {atomic:73, symbol:'Ta', name:'Tantalum', group:ChemicalGroup.TransitionMetal, mass:180.9479, weight:181, radioactive:false, artificially:false},
  {atomic:74, symbol:'W', name:'Tungsten', group:ChemicalGroup.TransitionMetal, mass:183.84, weight:184, radioactive:false, artificially:false},
  {atomic:75, symbol:'Re', name:'Rhenium', group:ChemicalGroup.TransitionMetal, mass:186.207, weight:186, radioactive:false, artificially:false},
  {atomic:76, symbol:'Os', name:'Osmium', group:ChemicalGroup.TransitionMetal, mass:190.23, weight:190, radioactive:false, artificially:false},
  {atomic:77, symbol:'Ir', name:'Iridium', group:ChemicalGroup.TransitionMetal, mass:192.217, weight:192, radioactive:false, artificially:false},
  {atomic:78, symbol:'Pt', name:'Platinum', group:ChemicalGroup.TransitionMetal, mass:195.078, weight:195, radioactive:false, artificially:false},
  {atomic:79, symbol:'Au', name:'Gold', group:ChemicalGroup.TransitionMetal, mass:196.96657, weight:197, radioactive:false, artificially:false},
  {atomic:80, symbol:'Hg', name:'Mercury', group:ChemicalGroup.TransitionMetal, mass:200.59, weight:201, radioactive:false, artificially:false},
  {atomic:81, symbol:'Tl', name:'Thallium', group:ChemicalGroup.PostTransitionMetal, mass:204.3833, weight:204, radioactive:false, artificially:false},
  {atomic:82, symbol:'Pb', name:'Lead', group:ChemicalGroup.PostTransitionMetal, mass:207.2, weight:207, radioactive:false, artificially:false},
  {atomic:83, symbol:'Bi', name:'Bismuth', group:ChemicalGroup.PostTransitionMetal, mass:208.9804, weight:209, radioactive:true, artificially:false},
  {atomic:84, symbol:'Po', name:'Polonium', group:ChemicalGroup.Metalloid, mass:208.98243, weight:209, radioactive:true, artificially:false},
  {atomic:85, symbol:'At', name:'Astatine', group:ChemicalGroup.Halogen, mass:209.98715, weight:210, radioactive:true, artificially:false},
  {atomic:86, symbol:'Rn', name:'Radon', group:ChemicalGroup.NobleGas, mass:222.01758, weight:222, radioactive:true, artificially:false},
  {atomic:87, symbol:'Fr', name:'Francium', group:ChemicalGroup.AlkaliMetal, mass:223.01973, weight:223, radioactive:true, artificially:false},
  {atomic:88, symbol:'Ra', name:'Radium', group:ChemicalGroup.AlkalineEarthMetal, mass:226.02541, weight:226, radioactive:true, artificially:false},
  {atomic:89, symbol:'Ac', name:'Actinium', group:ChemicalGroup.Actinide, mass:227, weight:227.02775, radioactive:true, artificially:false},
  {atomic:90, symbol:'Th', name:'Thorium', group:ChemicalGroup.Actinide, mass:232.0381, weight:232, radioactive:true, artificially:false},
  {atomic:91, symbol:'Pa', name:'Protactinium', group:ChemicalGroup.Actinide, mass:231.03588, weight:231, radioactive:true, artificially:false},
  {atomic:92, symbol:'U', name:'Uranium', group:ChemicalGroup.Actinide, mass:238.0289, weight:238, radioactive:true, artificially:false},
  {atomic:93, symbol:'Np', name:'Neptunium', group:ChemicalGroup.Actinide, mass:237.048172, weight:237, radioactive:true, artificially:true},
  {atomic:94, symbol:'Pu', name:'Plutonium', group:ChemicalGroup.Actinide, mass:244.0642, weight:244, radioactive:true, artificially:true},
  {atomic:95, symbol:'Am', name:'Americium', group:ChemicalGroup.Actinide, mass:243.06138, weight:243, radioactive:true, artificially:true},
  {atomic:96, symbol:'Cm', name:'Curium', group:ChemicalGroup.Actinide, mass:247.07035, weight:247, radioactive:true, artificially:true},
  {atomic:97, symbol:'Bk', name:'Berkelium', group:ChemicalGroup.Actinide, mass:247.07031, weight:247, radioactive:true, artificially:true},
  {atomic:98, symbol:'Cf', name:'Californium', group:ChemicalGroup.Actinide, mass:251.07959, weight:251, radioactive:true, artificially:true},
  {atomic:99, symbol:'Es', name:'Einsteinium', group:ChemicalGroup.Actinide, mass:252.083, weight:252, radioactive:true, artificially:true},
  {atomic:100, symbol:'Fm', name:'Fermium', group:ChemicalGroup.Actinide, mass:257.09511, weight:257, radioactive:true, artificially:true},
  {atomic:101, symbol:'Md', name:'Mendelevium', group:ChemicalGroup.Actinide, mass:258.09843, weight:258, radioactive:true, artificially:true},
  {atomic:102, symbol:'No', name:'Nobelium', group:ChemicalGroup.Actinide, mass:259.101, weight:259, radioactive:true, artificially:true},
  {atomic:103, symbol:'Lr', name:'Lawrencium', group:ChemicalGroup.Actinide, mass:262.12, weight:262, radioactive:true, artificially:true},
  {atomic:104, symbol:'Rf', name:'Rutherfordium', group:ChemicalGroup.TransitionMetal, mass:267.122, weight:263, radioactive:true, artificially:true},
  {atomic:105, symbol:'Db', name:'Dubnium', group:ChemicalGroup.TransitionMetal, mass:268.126, weight:268, radioactive:true, artificially:true},
  {atomic:106, symbol:'Sg', name:'Seaborgium', group:ChemicalGroup.TransitionMetal, mass:271.134, weight:271, radioactive:true, artificially:true},
  {atomic:107, symbol:'Bh', name:'Bohrium', group:ChemicalGroup.TransitionMetal, mass:274.144, weight:270, radioactive:true, artificially:true},
  {atomic:108, symbol:'Hs', name:'Hassium', group:ChemicalGroup.TransitionMetal, mass:277.152, weight:270, radioactive:true, artificially:true},
  {atomic:109, symbol:'Mt', name:'Meitnerium', group:ChemicalGroup.TransitionMetal, mass:278.156, weight:278, radioactive:true, artificially:true},
  {atomic:110, symbol:'Ds', name:'Darmstadtium', group:ChemicalGroup.TransitionMetal, mass:281.165, weight:281, radioactive:true, artificially:true},
  {atomic:111, symbol:'Rg', name:'Roentgenium', group:ChemicalGroup.TransitionMetal, mass:282.169, weight:281, radioactive:true, artificially:true},
  {atomic:112, symbol:'Cn', name:'Copernicium', group:ChemicalGroup.TransitionMetal, mass:285.177, weight:285, radioactive:true, artificially:true},
  {atomic:113, symbol:'Nh', name:'Nihonium', group:ChemicalGroup.PostTransitionMetal, mass:286.183, weight:286, radioactive:true, artificially:true},
  {atomic:114, symbol:'Fl', name:'Flerovium', group:ChemicalGroup.PostTransitionMetal, mass:289.191, weight:289, radioactive:true, artificially:true},
  {atomic:115, symbol:'Mc', name:'Moscovium', group:ChemicalGroup.PostTransitionMetal, mass:290.196, weight:289, radioactive:true, artificially:true},
  {atomic:116, symbol:'Lv', name:'Livermorium', group:ChemicalGroup.PostTransitionMetal, mass:293.205, weight:293, radioactive:true, artificially:true},
  {atomic:117, symbol:'Ts', name:'Tennessine', group:ChemicalGroup.Halogen, mass:294.211, weight:294, radioactive:true, artificially:true},
  {atomic:118, symbol:'Og', name:'Oganesson', group:ChemicalGroup.NobleGas, mass:294.214, weight:294, radioactive:true, artificially:true}
]

@Component({
  selector: 'app-kind',
  templateUrl: './kind.component.html',
  styleUrls: ['./kind.component.sass']
})
export class KindComponent implements OnInit {

  displayedColumns: string[] = [
    'atomic',
    'symbol',
    'name',
    'group',
    'mass',
    'radioactive',
    'artificially'
  ]

  dataSource = ELEMENT_DATA

  constructor() { }

  ngOnInit(): void {
  }

}
