import {
  Component,
  OnInit
} from '@angular/core'

import { Element } from 'src/app/models/element.model'

const ELEMENT_DATA: Element[] = [
  {atomic:1, symbol:'H', name:'Hydrogen', group:'Nonmetal', mass:1.0079, weight:1, radioactive:false, artificially:false},
  {atomic:2, symbol:'He', name:'Helium', group:'Noble Gas', mass:4.0026, weight:4, radioactive:false, artificially:false},
  {atomic:3, symbol:'Li', name:'Lithium', group:'Alkali Metal', mass:6.941, weight:7, radioactive:false, artificially:false},
  {atomic:4, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:5, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:6, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:7, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:8, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:9, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:10, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:11, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:12, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:13, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:14, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:15, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:16, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:17, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:18, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:19, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:20, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:21, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:22, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:23, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:24, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:25, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:26, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:27, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:28, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:29, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:30, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:31, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:32, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:33, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:34, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:35, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:36, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:37, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:38, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:39, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:40, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:41, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:42, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:43, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:44, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:45, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:46, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:47, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:48, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:49, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:50, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:51, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:52, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:53, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:54, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:55, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:56, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:57, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:58, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:59, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:60, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:61, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:62, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:63, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:64, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:65, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:66, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:67, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:68, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:69, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:70, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:71, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:72, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:73, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:74, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:75, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:76, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:77, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:78, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:79, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:80, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:81, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:82, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:83, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:84, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:85, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:86, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:87, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:88, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:89, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:90, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:91, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:92, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:93, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:94, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:95, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:96, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:97, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:98, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:99, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:100, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:101, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:102, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:103, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:104, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:105, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:106, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:107, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:108, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:109, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:110, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:111, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:112, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:113, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:114, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:115, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:116, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:117, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null},
  {atomic:118, symbol:null, name:null, group:null, mass:null, weight:null, radioactive:null, artificially:null}
]

@Component({
  selector: 'app-kind',
  templateUrl: './kind.component.html',
  styleUrls: ['./kind.component.sass']
})
export class KindComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
